### ISSUE TITLE
Further doc link doesn't work

### ISSUE THREAD

**Issue by JonathonRP** [jgchk/trpc-svelte-query#1]
looking for further docs on this lib, and the link doesn't work.
having an issue with getClientContext is null

**Comment by jgchk** [comment]
you're right on the docs link, i will update that asap

on the getClientContext is null issue, make sure you're calling setContextClient in your `routes/+layout.svelte` file:
```svelte
<script lang="ts">
  import { QueryClientProvider } from '@tanstack/svelte-query'
  import { setContextClient } from '$lib/trpc'
  import type { LayoutData } from './$types'

  export let data: LayoutData

  setContextClient(data.trpc)
</script>

<QueryClientProvider client={data.trpc.queryClient}>
  <slot />
</QueryClientProvider>
```

**Comment by JonathonRP** [comment]
I am setting the client context in +layout.svelte.
Would the position of calling setClientContext matter?

**Comment by jgchk** [comment]
hmm... position shouldnt matter. what file are you calling getClientContext in?

**Comment by JonathonRP** [comment]
I'm calling it in a +page.svelte

**Comment by jgchk** [comment]
can you post your repo or a minimal reproduction?

**Comment by JonathonRP** [comment]
Ok I think I solved this, I was using +page.server.ts and awaiting api.buxfer in there from the parent() but this must be done in +page.ts. my error in not closely reading the doc example. Thanks for your help!
